/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reinas8;

import java.util.ArrayList;
import java.util.Collections;

/**
 *
 * @author Bacs
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        pan=new Panel(this.Jpdibujo);
    }
    
    Poblacion pob;
    FitFunc ff;
    Seleccion sel;
    Panel pan;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Jpdibujo = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Sgen = new javax.swing.JSpinner();
        Sind = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        Sreinas = new javax.swing.JSpinner();
        btnGraf = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtApt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout JpdibujoLayout = new javax.swing.GroupLayout(Jpdibujo);
        Jpdibujo.setLayout(JpdibujoLayout);
        JpdibujoLayout.setHorizontalGroup(
            JpdibujoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        JpdibujoLayout.setVerticalGroup(
            JpdibujoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 492, Short.MAX_VALUE)
        );

        jLabel1.setText("Num. de Generaciones:");

        jLabel2.setText("Num. de Individuos");

        jLabel3.setText("Num de Reinas");

        btnGraf.setText("graficar");
        btnGraf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrafActionPerformed(evt);
            }
        });

        jLabel5.setText("Aptitudes:");

        txtApt.setEditable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(Sgen, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(Sind, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(btnGraf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(Sreinas, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtApt, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(Sgen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(Sreinas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGraf)
                    .addComponent(jLabel5)
                    .addComponent(txtApt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Jpdibujo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Jpdibujo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGrafActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrafActionPerformed
        int t=(int)this.Sreinas.getValue();
        int p=(int)Sind.getValue();
        ArrayList<Integer> idx=new ArrayList<Integer>();
        ArrayList<Integer> actitud=new ArrayList<Integer>();
        ff = new FitFunc();
        pob=new Poblacion(p);
        pob.inicializa((int)Sreinas.getValue());
        for(Individuo ind : pob.po){
            actitud.add(ff.evaluate(ind));
        }
        graficar(pob.po.get(mejor(actitud)), t);
        sel = new Seleccion(actitud);
        for(int i=0;i<p;i++){
            idx.add(sel.seleccion());
        }
        ArrayList<Individuo> generacion=new  ArrayList<Individuo>();
        if(p%2!=0){
            generacion.add(pob.po.get(1));
        }
        for(int i=0;i<p/2;i++){
            generacion.addAll(pob.po.get(idx.get(i)).cruza(pob.po.get(idx.get(p-i-1))));
        }
        int por=(int)Math.ceil(p*0.05);
        for(int i=0;i<por;i++){
            generacion.get((int)(Math.random()*p)).mutar();
        }
        for(int x=0; x<(int)Sgen.getValue();x++){
            idx=new ArrayList<Integer>();
            pob.po=generacion;
            actitud=new ArrayList<Integer>();
            for(Individuo ind : pob.po){
                actitud.add(ff.evaluate(ind));
            }
            sel = new Seleccion(actitud);
            graficar(pob.po.get(mejor(actitud)), t);
            for(int i=0;i<p;i++){
                idx.add(sel.seleccion());
            }   
            generacion=new  ArrayList<Individuo>();
            if(p%2!=0){
                generacion.add(pob.po.get(1));
            }
            for(int i=0;i<p/2;i++){
                generacion.addAll(pob.po.get(idx.get(i)).cruza(pob.po.get(idx.get(p-i-1))));
            }
            por=(int)Math.ceil(p*0.05);
            for(int i=0;i<por;i++){
                generacion.get((int)(Math.random()*p)).mutar();
            }
        }
    }//GEN-LAST:event_btnGrafActionPerformed
    
    public int mejor(ArrayList<Integer> act){
        int idx=0;
        
        for(int i=0;i<act.size();i++){
            if(act.get(idx)>act.get(i)){
                idx=i;
            }
        }
        txtApt.setText(act.get(idx)+"");
        return idx;
    }
    
    public void graficar(Individuo ind, int t){
        for(int i=0;i<ind.cromosoma.size();i++){
            //System.out.println("x"+ind.cromosoma.get(i).getX()+" y"+ind.cromosoma.get(i).getY());
        }
        
        pan.dibujar(t, ind.cromosoma);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Jpdibujo;
    private javax.swing.JSpinner Sgen;
    private javax.swing.JSpinner Sind;
    private javax.swing.JSpinner Sreinas;
    private javax.swing.JButton btnGraf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtApt;
    // End of variables declaration//GEN-END:variables
}
